### ISSUE TITLE
OSError: b"Unknown option '-1'. Aborting."

### ISSUE THREAD

**Issue by Freekers** [puddly/android-otp-extractor#23]
I'm running your script on my Windows 10 Pro machine with Python 3.6.4 and ADB 1.0.3.9.
My rooted Android 4.4.2 tablet with kernel 3.4.0 is connected via USB with debugging enabled.

When executing the script, I get the following error:
```
C:\Program Files (x86)\Minimal ADB and Fastboot>py -3 D:\Downloads\android-otp-extractor-master\extract_otp_tokens.py
[2018-10-09 19:09:28,088]     INFO [<module>:519] Checking for root by listing the contents of data/data. You might have to grant ADB temporary root access.
Traceback (most recent call last):
  File "D:\Downloads\android-otp-extractor-master\extract_otp_tokens.py", line 521, in <module>
    if not adb_list_dir(args.data):
  File "D:\Downloads\android-otp-extractor-master\extract_otp_tokens.py", line 175, in adb_list_dir
    lines = adb_fast_run(f'su -c "ls -1 {shlex.quote(str(path))}"', prefix=b'ls: ')
  File "D:\Downloads\android-otp-extractor-master\extract_otp_tokens.py", line 167, in adb_fast_run
    raise IOError(message)
OSError: b"Unknown option '-1'. Aborting."
```
How can I solve this issue?

Thank you!

**Comment by puddly** [comment]
I don't think I've tested any Android version before 5.0. What ROM are you using?

**Comment by Freekers** [comment]
Thanks for your reply.

I am using the stock ROM of my LG-V500 tablet.
It has build-version KOT49I.V50020f and software-version: V50020f if that helps.

**Comment by puddly** [comment]
Thanks, I can replicate the issue. I'll see what I can do.

**Comment by Freekers** [comment]
Thank you very much for the quick fix, it works now!! Awesome!
PS. You might want to add Busybox as a requirement in the README :)
Kind regards.

**Comment by puddly** [comment]
@Freekers I just need `base64` and `ls -1`, both of which should be provided by either `busybox` or `toybox` (the latter is included in all recent versions of Android). For some reason Android 4.4's `/usr/bin/ls` binary does not support `-1` while `busybox ls` does.

**Comment by Freekers** [comment]
> 
> 
> @Freekers I just need `base64` and `ls -1`, both of which should be provided by either `busybox` or `toybox` (the latter is included in all recent versions of Android). For some reason Android 4.4's `/usr/bin/ls` binary does not support `-1` while `busybox ls` does.

I had to install `busybox` because without it kept failing:

```
C:\Program Files (x86)\Minimal ADB and Fastboot>py -3 D:\Downloads\android-otp-extractor-master\extract_otp_tokens.py
[2018-10-09 21:21:15,765]     INFO [<module>:544] Testing if your phone uses toybox...
[2018-10-09 21:21:15,941]  WARNING [<module>:556] Could not list /: Binary not found
[2018-10-09 21:21:15,942]     INFO [<module>:544] Testing if your phone uses busybox...
[2018-10-09 21:21:16,248]  WARNING [<module>:556] Could not list /: Binary not found
[2018-10-09 21:21:16,248]    ERROR [<module>:563] Could not find a suitable file reading interface!
```

**Comment by puddly** [comment]
Those older Android builds are really something. It looks like your device doesn't have either binary.

**Comment by Freekers** [comment]
By default, it doesn't ship with either binary. However, after installing 'BusyBox' from the Playstore, I was able to successfully run your script. Hence my note to add that BusyBox is required for Android 4 in the README :)
Kind regards
