### ISSUE TITLE
ADB Permission problem

### ISSUE THREAD

**Issue by walent021** [puddly/android-otp-extractor#37]
Hey, do you know how can i fix this?
```
C:\Program Files (x86)\Minimal ADB and Fastboot>python -m android_otp_extractor
2020-07-22 23:39:36 DESKTOP-5URJ0ND android_otp_extractor.adb[16904] INFO Testing if your phone uses binary: 'toybox'
2020-07-22 23:39:36 DESKTOP-5URJ0ND android_otp_extractor.adb[16904] INFO Listing contents of / as root
Traceback (most recent call last):
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\__main__.py", line 3, in <module>
    main()
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\cli.py", line 53, in main
    adb = guess_adb_interface(args.data)
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\adb.py", line 115, in guess_adb_interface
    if not test.list_dir('/'):
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\adb.py", line 78, in list_dir
    lines = self.run(f'{self.binary} ls -1 {shlex.quote(str(path))}', prefix=b'ls: ', root=True)
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\adb.py", line 57, in run
    raise ValueError(f'adb command failed: {lines}')
ValueError: adb command failed: [b'Permission denied\r\n']
```

**Comment by puddly** [comment]
Can you re-run the command with maximum logging verbosity (`-vvv`)?

**Comment by walent021** [comment]
Phone is rooted with magisk, adb shell works.

`C:\Program Files (x86)\Minimal ADB and Fastboot>python -m android_otp_extractor -vvv
2020-07-23 13:19:46 DESKTOP-5URJ0ND android_otp_extractor.adb[7716] INFO Testing if your phone uses binary: 'toybox'
2020-07-23 13:19:46 DESKTOP-5URJ0ND android_otp_extractor.adb[7716] INFO Listing contents of / as root
2020-07-23 13:19:46 DESKTOP-5URJ0ND android_otp_extractor.adb[7716] DEBUG Listing directory /
2020-07-23 13:19:46 DESKTOP-5URJ0ND android_otp_extractor.adb[7716] TRACE Running ['adb', 'shell', 'su -c "toybox ls -1 /; echo 3bb22bb739c29e435151cb38"']
2020-07-23 13:19:46 DESKTOP-5URJ0ND android_otp_extractor.adb[7716] TRACE Read: b'Permission denied\r\n'
Traceback (most recent call last):
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\__main__.py", line 3, in <module>
    main()
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\cli.py", line 53, in main
    adb = guess_adb_interface(args.data)
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\adb.py", line 115, in guess_adb_interface
    if not test.list_dir('/'):
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\adb.py", line 78, in list_dir
    lines = self.run(f'{self.binary} ls -1 {shlex.quote(str(path))}', prefix=b'ls: ', root=True)
  File "C:\Users\walen\AppData\Local\Programs\Python\Python38\lib\site-packages\android_otp_extractor\adb.py", line 57, in run
    raise ValueError(f'adb command failed: {lines}')
ValueError: adb command failed: [b'Permission denied\r\n']
`

**Comment by puddly** [comment]
It works fine for me on Windows so it might be something with your environment. Can you try running these commands through Command Prompt?

 1. `python -c "__import__('subprocess').check_call(['adb', 'shell', 'su -c \'ls -1 /\''])"`
 2. `adb shell "su -c 'ls -1 /'"`
 3. `adb shell` and then running `su -c "ls -1 /"` within the shell

**Comment by walent021** [comment]
I have changed from MIUI 11 to AOSP Android 10 yesterday, and now it works, so I can't say for sure what was the problem.

**Comment by puddly** [comment]
Ah, MIUI may have been the issue. I do not have any phones that run MIUI.
