### ISSUE TITLE
Error trying to read Duo accounts

### ISSUE THREAD

**Issue by kstorbakken** [puddly/android-otp-extractor#42]
Try to run this and it fails on reading back Duo accounts, which is the only app I'm actually using and want the data out of.

`021-04-21 23:14:33 localhost.localdomain android_otp_extractor.adb[3141] INFO Testing if your phone uses binary: 'toybox'
2021-04-21 23:14:33 localhost.localdomain android_otp_extractor.adb[3141] INFO Checking if adb already runs as root
2021-04-21 23:14:33 localhost.localdomain android_otp_extractor.adb[3141] INFO Listing contents of / as root
2021-04-21 23:14:33 localhost.localdomain android_otp_extractor.adb[3141] INFO Reading and hashing contents of build.prop as root
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.adb[3141] INFO Using command line utility binary: 'toybox'
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Reading Authy accounts
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Found 0 accounts (0 new)
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Reading FreeOTP accounts
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Found 0 accounts (0 new)
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Reading FreeOTP+ accounts
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Found 0 accounts (0 new)
2021-04-21 23:14:34 localhost.localdomain android_otp_extractor.apps[3141] INFO Reading Duo accounts
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kent/.local/lib/python3.9/site-packages/android_otp_extractor/__main__.py", line 3, in <module>
    main()
  File "/home/kent/.local/lib/python3.9/site-packages/android_otp_extractor/cli.py", line 62, in main
    accounts = apps.read_accounts(adb, enabled_apps)
  File "/home/kent/.local/lib/python3.9/site-packages/android_otp_extractor/apps.py", line 353, in read_accounts
    new = list(app.extractor(adb))
  File "/home/kent/.local/lib/python3.9/site-packages/android_otp_extractor/apps.py", line 116, in read_duo_accounts
    secret = base64.b32decode(account['otpGenerator']['otpSecret'])
  File "/usr/lib64/python3.9/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
`

Hoping to get my accounts out of Duo before switching phones. Any help appreciated!

**Comment by kstorbakken** [comment]
This was on Lineage OS 16 as well with Magisk and busybox installed. 

I managed to retrieve all my Duo OTP accounts by issuing `find . -name accounts.json`. The Duo folder with that file was the only result and I just copied all the data out of it. It looks like I'm able to put the otpSecret line from that file right into Aegis as the secret key and it works.

**Comment by puddly** [comment]
What do the characters in the bad account's `otpGenerator.otpSecret` look like? The Python built-in `base64.b32decode()` seems to dislike some part of it.

**Comment by kstorbakken** [comment]
I noticed that as well. I'm able to run all of the otpSecret's through a cyberchef base64 decode and it comes out okay on all of them.

All of the characters in them are alphabetical and numerical, no symbols. A-Z a-z 0-9. They're all varying lengths though, some are 16 characters, some 32. One of them is a lengthy 304 characters, but I imported it to Aegis and it works fine.

**Comment by puddly** [comment]
Hmm. When I last used Duo the secrets were base32-encoded, not base64, so that would likely explain it. It's a bit difficult to debug these types things when you're dealing with secrets at every step...

When you say "it works fine", do you mean that Aegis just recognizes it as a secret and generates some sort of OTP token, or that it's actually a valid Duo OTP token that you can use to authenticate with? 304 characters is excessively long for a secret. Duo may have begun transitioning to the Android KeyStore as well.

**Comment by kstorbakken** [comment]
I hear you, suppose I could generate a dummy account on something and give you an example key. It's getting late here, but I'll get you one soon. 

When I say it works, I mean I took the string directly from the otpSecret line, and put it right into Aegis and I can generate codes that work to log me in. That's without doing a decode of any kind on the otpSecret either.

**Comment by puddly** [comment]
I don't have any more online accounts to register with Duo at the moment so if you say that the secret can be base64-encoded now, that should be enough. Thanks!
