### ISSUE TITLE
Authenticator Plus

### ISSUE THREAD

**Issue by p1r473** [puddly/android-otp-extractor#46]
Hi, I've started looking into how we can add support for some more popular Authenticator apps.
I am going to open this and close it- I don't need it personally- but if you want to implement it, I will reopen this and I am happy to test.
Happy to do the same for any other authenticator too and help test- I really like this project and happy to help. I have wanted a way of extracting OTPauths out of Authenticators for YEARS.

Authenticator Plus is a common one I've seen on the play store for years:
Data is stored in SQLCipher encrypted database at
/sdcard/AuthenticatorPlus/.synced_authplus.db

A master password is required to use Authenticator Plus.
Master password is stored in the Android local database.
In rooted device, PIN lock is mandated, and your master password is encrypted with your PIN

More technical directions:
https://authenticatorplus.freshdesk.com/support/solutions/articles/5000541895-technical-details-of-authenticator-plus

Play store link:
https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus&hl=en_CA&gl=US

**Comment by puddly** [comment]
Thanks! For visibility, it's best to keep issues open even if they're not actively being worked on.

It's a paid app and I don't use the Google Play ecosystem myself so it's going to be difficult to get a working setup. If you yourself own this app and can make a databases with all of the account types and the few encryption combinations, I can probably add support for it.

**Comment by p1r473** [comment]
Pin: 1234
Master password: 1234567890
File goes in /sdcard/AuthenticatorPlus/.synced_authplus.db
https://www.sendspace.com/file/5izv67

**Comment by puddly** [comment]
Thanks! I was able to decrypt the database but there's nothing interesting in it:

```SQL
CREATE TABLE accounts (_id INTEGER PRIMARY KEY, position INTEGER, email TEXT NOT NULL, secret TEXT NOT NULL,  counter INTEGER DEFAULT 0, type INTEGER, provider INTEGER DEFAULT 0, timestamp TEXT NOT NULL, uid TEXT NOT NULL, issuer TEXT, original_name TEXT, category TEXT NOT NULL DEFAULT 'All Accounts');
CREATE TABLE metadata (_id INTEGER PRIMARY KEY, timestamp TEXT NOT NULL);
CREATE TABLE deleted (uid TEXT NOT NULL, timestamp TEXT NOT NULL);
CREATE TABLE trial (timestamp TEXT NOT NULL);
CREATE TABLE category (name TEXT NOT NULL, _id INTEGER PRIMARY KEY,  position INTEGER DEFAULT 0, timestamp TEXT NOT NULL);
CREATE TABLE securid  (DEVID_COLUMN TEXT NOT NULL);
CREATE TRIGGER DELETE_OLD_DELETED_ROWS AFTER INSERT ON deleted FOR EACH ROW BEGIN DELETE FROM deleted WHERE DATE(timestamp) < DATE('now', '-30 days'); END;

INSERT INTO securid VALUES('33E9397FE9ADA38A2E29C3D9');
INSERT INTO metadata VALUES(1,'2021-05-27 15:41:27');
```

The app itself should have a database in `/data/data/com.mufri.authenticatorplus/`. What does `adb shell 'find /data/data/com.mufri.authenticatorplus/'` tell you?

**Comment by p1r473** [comment]
Whoops, sorry about that!
I did find some goodies in there!
https://www.sendspace.com/file/14d0dv

**Comment by p1r473** [comment]
Sorry for the delay, I'm having a hell of a time getting pysqlcipher3 on Windows, and I can't get ADB working on my SBC
Will test it when I am able to get this library working
There weren't any alternatives that may be a little easier to install? The pysqlcipher3 Windows instructions are quite complex

**Comment by puddly** [comment]
From what I understand, SQLCipher is built on top of SQLite. You sort of have to create a custom build of SQLite to use it. Maybe it's possible to decrypt the database file directly.

**Comment by p1r473** [comment]
I am installing Linux on my desktop (dual partition)
Soon as it's done, I'll post back with your current implementation's results.

**Comment by puddly** [comment]
Yeah, short of re-implementing SQLCipher in Python, there's unfortunately no way to load a SQLCipher-encrypted database without compiling SQLCipher's modified SQLite. 

For packaged Android apps (and macOS + Linux users) this isn't an issue but unless you already have a proper Windows development environment, it's a massive pain to install everything.

**Comment by p1r473** [comment]
I made a Debian10 Virtual Machine where I am now set up but I seem to be having trouble even installing pysqlcipher3 directly with pip
```
root@Debian10:~/Desktop/pysqlcipher3-1.0.4# pip3 install pysqlcipher3
Collecting pysqlcipher3
  Using cached pysqlcipher3-1.0.4.tar.gz (102 kB)
Building wheels for collected packages: pysqlcipher3
  Building wheel for pysqlcipher3 (setup.py) ... done
  WARNING: Legacy build of wheel for 'pysqlcipher3' created no files.
  Command arguments: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4qvo4sdn/pysqlcipher3_f836ed0e309d4ad8985f9b79f816b9d3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4qvo4sdn/pysqlcipher3_f836ed0e309d4ad8985f9b79f816b9d3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_z3axtxx
  Command output: [use --verbose to show]
  Running setup.py clean for pysqlcipher3
Failed to build pysqlcipher3
Installing collected packages: pysqlcipher3
    Running setup.py install for pysqlcipher3 ... done
Successfully installed pysqlcipher3
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
```


also tried to install with python3 setup.py install and downloading the pysqlcipher3 files
```
root@Debian10:~/Desktop/pysqlcipher3-1.0.4# python3 setup.py install
running install
running bdist_egg
running egg_info
writing pysqlcipher3.egg-info/PKG-INFO
writing dependency_links to pysqlcipher3.egg-info/dependency_links.txt
writing top-level names to pysqlcipher3.egg-info/top_level.txt
reading manifest file 'pysqlcipher3.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'pysqlcipher3.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/pysqlcipher3
copying lib/__init__.py -> build/lib.linux-x86_64-3.7/pysqlcipher3
copying lib/dump.py -> build/lib.linux-x86_64-3.7/pysqlcipher3
copying lib/dbapi2.py -> build/lib.linux-x86_64-3.7/pysqlcipher3
creating build/lib.linux-x86_64-3.7/pysqlcipher3/test
copying lib/test/__init__.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test
creating build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/factory.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/__init__.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/hooks.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/userfunctions.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/sqlcipher.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/dump.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/dbapi.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/types.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/regression.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
copying lib/test/python3/transactions.py -> build/lib.linux-x86_64-3.7/pysqlcipher3/test/python3
running build_ext
Builds a C extension linking against libsqlcipher library
building 'pysqlcipher3._sqlite3' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
creating build/temp.linux-x86_64-3.7/src/python3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMODULE_NAME="pysqlcipher3.dbapi2" -I/usr/include/python3.7m -c src/python3/module.c -o build/temp.linux-x86_64-3.7/src/python3/module.o
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by p1r473** [comment]
Think I finally got it working on my Debian10 VM.
```
sudo apt update
sudo apt upgrade
sudo apt install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
sudo apt-get install libsqlcipher-dev
sudo apt install build-essential git cmake libsqlite3-dev
sudo apt install sqlcipher
git clone https://github.com/rigglemania/pysqlcipher3
cd pysqlcipher3
python3 setup.py build
sudo python3 setup.py install

if installing in virtual environment also do
pip install pysqlcipher3 in the environment

if sys.platform.lower() == 'linux':
  try:
     from pysqlcipher3 import dbapi2 as sqlite3
  except:
     import sqlite3
```

**Comment by p1r473** [comment]
It works great! Holy smokes. 1 day of trying to get this library working and it works beautifully on the first try.
You ask for the masterpassword, however you never ask for the PIN. How did you get the PIN that decrypts the masterpassword?

```
root@Debian10:~/Desktop/pysqlcipher3# python3 -m android_otp_extractor --include authenticator_plus -v
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] INFO Testing if your phone uses binary: 'toybox'
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] INFO Checking if adb already runs as root
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] INFO Attempting to enable adb root
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] INFO Listing contents of / as root
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Listing directory /
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] INFO Reading and hashing contents of build.prop as root
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Hashing file $ANDROID_ROOT/build.prop
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_ROOT/build.prop
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Successfully read 2018 bytes
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Hashing file $ANDROID_ROOT/build.prop
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_ROOT/build.prop
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Successfully read 2018 bytes
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] INFO Using command line utility binary: 'toybox'
2021-06-01 12:55:56 Debian10 android_otp_extractor.apps[9696] INFO Reading Authenticator Plus accounts
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_DATA/data/com.mufri.authenticatorplus/databases/databases
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Successfully read 9216 bytes
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_DATA/data/com.mufri.authenticatorplus/databases/databases
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Successfully read 9216 bytes
2021-06-01 12:55:56 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_DATA/data/com.mufri.authenticatorplus/databases/databases-journal
2021-06-01 12:55:57 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_DATA/data/com.mufri.authenticatorplus/databases/databases-wal
2021-06-01 12:55:57 Debian10 android_otp_extractor.adb[9696] DEBUG Trying to read file $ANDROID_DATA/data/com.mufri.authenticatorplus/databases/databases-shm
Enter the Authenticator Plus master password: 
2021-06-01 12:56:00 Debian10 android_otp_extractor.apps[9696] DEBUG Found an account <TOTPAccount(secret='JBSWY3DPEHPK3PXP', label='alice@google.com', digits=6, period=30, algorithm='SHA1')>
2021-06-01 12:56:00 Debian10 android_otp_extractor.apps[9696] INFO Found 1 accounts (1 new)
2021-06-01 12:56:00 Debian10 android_otp_extractor.cli[9696] INFO Found account: otpauth://totp/alice%40google.com?algorithm=SHA1&digits=6&issuer=Example&period=30&secret=JBSWY3DPEHPK3PXP
```

**Comment by puddly** [comment]
Glad it works!

> You ask for the masterpassword, however you never ask for the PIN. How did you get the PIN that decrypts the masterpassword?

Maybe the PIN is just to prevent the app from being opened? Nothing other than the password is necessary.

Encrypting the password with a PIN also seems a little superfluous, since you could just use `password|pin` as the password itself and gain the security benefits of using both.

**Comment by p1r473** [comment]
> Glad it works!
> 
> > You ask for the masterpassword, however you never ask for the PIN. How did you get the PIN that decrypts the masterpassword?
> 
> Maybe the PIN is just to prevent the app from being opened? Nothing other than the password is necessary.
> 
> Encrypting the password with a PIN also seems a little superfluous, since you could just use `password|pin` as the password itself and gain the security benefits of using both.

Yep, I deleted the whole database, made a new PIN, new masterpassword, started from scratch, and it worked great,
Thanks @puddly 
Would you like me to proactively do this for additional authenticators? I was going to go through the play store and start with the next top downloaded authenticator.
Or, if youre busy, we can do it after LastPass Authenticator which I know is in the works.

**Comment by p1r473** [comment]
> Glad it works!
> 
> > You ask for the masterpassword, however you never ask for the PIN. How did you get the PIN that decrypts the masterpassword?
> 
> Maybe the PIN is just to prevent the app from being opened? Nothing other than the password is necessary.
> 
> Encrypting the password with a PIN also seems a little superfluous, since you could just use `password|pin` as the password itself and gain the security benefits of using both.

From the documentation:
`In rooted device, PIN lock is mandated, and your master password is encrypted with your PIN`

So the explanation I think is if I give the masterpassword directly, we are bypassing the whole pin step.

**Comment by p1r473** [comment]
@puddly  If you want to have a TryCatch Exception for entering the wrong master password:
```
2021-06-01 13:25:25 Debian10 android_otp_extractor.adb[1093] INFO Using command line utility binary: 'toybox'
2021-06-01 13:25:25 Debian10 android_otp_extractor.apps[1093] INFO Reading Authenticator Plus accounts
Enter the Authenticator Plus master password: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/cli.py", line 62, in main
    accounts = apps.read_accounts(adb, enabled_apps)
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/apps.py", line 416, in read_accounts
    new = list(app.extractor(adb))
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/apps.py", line 393, in read_authenticator_plus_accounts
    cursor.execute('SELECT * FROM accounts;')
pysqlcipher3.dbapi2.DatabaseError: file is encrypted or is not a database
```

**Comment by p1r473** [comment]
Additionally,
If you enter an invalid secret, you might want to have an exception:
```
2021-06-01 13:25:57 Debian10 android_otp_extractor.adb[1126] INFO Using command line utility binary: 'toybox'
2021-06-01 13:25:57 Debian10 android_otp_extractor.apps[1126] INFO Reading Authenticator Plus accounts
Enter the Authenticator Plus master password: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/cli.py", line 62, in main
    accounts = apps.read_accounts(adb, enabled_apps)
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/apps.py", line 416, in read_accounts
    new = list(app.extractor(adb))
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/apps.py", line 396, in read_authenticator_plus_accounts
    secret = lenient_base32_decode(row['secret'])
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/otp.py", line 13, in lenient_base32_decode
    return base64.b32decode(data)
  File "/usr/lib/python3.7/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
```

**Comment by puddly** [comment]
Does the app still display a code if your secret isn't base-32?

**Comment by p1r473** [comment]
How can I test that? Can you give me a secret that isnt Base32 for testing?

**Comment by puddly** [comment]
You mentioned that you entered an "invalid secret" but the row was still written to the database so it seems like the app displays a code for it, right?

**Comment by p1r473** [comment]
Yes, I confirmed the app still displays a code for this entry
I used secret `hjjkhjhgjhk` and generated a qr code here https://stefansundin.github.io/2fa-qr/

Output of app
```
root@Debian10:~# python3 -m android_otp_extractor --include authenticator_plus
2021-06-01 13:33:33 Debian10 android_otp_extractor.adb[2484] INFO Testing if your phone uses binary: 'toybox'
2021-06-01 13:33:33 Debian10 android_otp_extractor.adb[2484] INFO Checking if adb already runs as root
2021-06-01 13:33:33 Debian10 android_otp_extractor.adb[2484] INFO Attempting to enable adb root
2021-06-01 13:33:33 Debian10 android_otp_extractor.adb[2484] INFO Listing contents of / as root
2021-06-01 13:33:33 Debian10 android_otp_extractor.adb[2484] INFO Reading and hashing contents of build.prop as root
2021-06-01 13:33:33 Debian10 android_otp_extractor.adb[2484] INFO Using command line utility binary: 'toybox'
2021-06-01 13:33:33 Debian10 android_otp_extractor.apps[2484] INFO Reading Authenticator Plus accounts
Enter the Authenticator Plus master password: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/cli.py", line 62, in main
    accounts = apps.read_accounts(adb, enabled_apps)
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/apps.py", line 416, in read_accounts
    new = list(app.extractor(adb))
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/apps.py", line 396, in read_authenticator_plus_accounts
    secret = lenient_base32_decode(row['secret'])
  File "/usr/local/lib/python3.7/dist-packages/android_otp_extractor/otp.py", line 13, in lenient_base32_decode
    return base64.b32decode(data)
  File "/usr/lib/python3.7/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
root@Debian10:~# 
```

**Comment by puddly** [comment]
Hmm. Without disassembling the app APK itself to see how it's parsing these types of secrets it's going to be very difficult to figure out how the app is interpreting it.

**Comment by p1r473** [comment]
No problem- everything is working fine really- I am just saying probably best to have a trycatch exception instead of crashing
Lets assume people wont be using gibberish codes
So far, the crashes Ive managed is
-Wrong masterpassword
-Non-base32 digit
Then, application wide, if ADB throws an error (device offline,no device found)
